package compi2.codex_latinus.frontend;

import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author michael
 */
public class MainWindow extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        setTitle("Codex Latinus");
        initStyles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        sidebarPanel = new javax.swing.JPanel();
        menuLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        openFileButton = new javax.swing.JButton();
        saveFileButton = new javax.swing.JButton();
        astButton = new javax.swing.JButton();
        synbolTableButton = new javax.swing.JButton();
        errorTableButton = new javax.swing.JButton();
        newFileButton3 = new javax.swing.JButton();
        contentPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        sidebarPanel.setBackground(new java.awt.Color(153, 51, 0));
        sidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLabel.setText("Menú de opciones");
        menuLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidebarPanel.add(menuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 10, 160, -1));
        sidebarPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, 10));

        openFileButton.setText("Abrir");
        openFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidebarPanel.add(openFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 164, 35));

        saveFileButton.setText("Guardar");
        saveFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidebarPanel.add(saveFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 125, 164, 35));

        astButton.setText("AST");
        astButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidebarPanel.add(astButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 164, 35));

        synbolTableButton.setText("Tabla de símbolos");
        synbolTableButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidebarPanel.add(synbolTableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 195, 164, 35));

        errorTableButton.setText("Tabla de errores");
        errorTableButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidebarPanel.add(errorTableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 164, 35));

        newFileButton3.setText("Nuevo");
        newFileButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidebarPanel.add(newFileButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 164, 35));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 192;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(sidebarPanel, gridBagConstraints);

        contentPane.setBackground(new java.awt.Color(153, 255, 51));
        contentPane.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 488;
        gridBagConstraints.ipady = 457;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
        getContentPane().add(contentPane, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton astButton;
    private javax.swing.JPanel contentPane;
    private javax.swing.JButton errorTableButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JButton newFileButton3;
    private javax.swing.JButton openFileButton;
    private javax.swing.JButton saveFileButton;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JButton synbolTableButton;
    // End of variables declaration//GEN-END:variables

    private void paintPanel(JPanel panel) {
        contentPane.removeAll();
        contentPane.add(panel);
        contentPane.revalidate();
        contentPane.repaint();
    }
    
        /**
     * Genera los estilos de los componentes.
     */
    private void initStyles() {
        menuLabel.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        menuLabel.setForeground(Color.white);

        SwingUtilities.updateComponentTreeUI(this);
    }
}
