package codex_latinus.frontend;

import codex_latinus.backend.Compiler;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTextArea;
import javax.swing.JTextPane;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import javax.swing.text.StyledDocument;

/**
 *
 * @author michael
 */
public class EditorPanel extends javax.swing.JPanel {

    private JTextPane codeTextArea;
    private JTextArea consoleTextArea;
    private JLabel statusLabel;
    private JButton compileButton;
    private LineNumberComponent lineNumberComponent;
    private Compiler compiler = new Compiler();
    private String result = "";
    private boolean isUpdatingHighlight = false;
    private Color colorSecciones;
    private Color colorKeywords;
    private Color colorTipos;
    private Color colorCadenas;
    private Color colorComentarios;

    /**
     * Creates new form EditorPanel
     */
    public EditorPanel() {
        initComponents();
        initCustomEditor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    public String getCodeText() {
        return codeTextArea.getText();
    }

    /**
     * Método para establecer el texto del código fuente en el editor.
     */
    public void setCodeText(String text) {
        codeTextArea.setText(text);
    }

    public String getResult() {
        return result;
    }
    
    public void setResult(String text) {
        this.result = text;
    }
    
    public void setConsoleTextArea(String text) {
        this.consoleTextArea.setText("");
    }

    /**
     * Inicializa los componentes del editor de código, consola, números de
     * línea, botón compilar y barra de estado.
     */
    private void initCustomEditor() {
        this.setLayout(new BorderLayout());

        inicializarColores();

        Color backgroundGray = new Color(240, 240, 240);
        this.setBackground(backgroundGray);

        codeTextArea = new JTextPane();
        codeTextArea.setFont(new Font("Monospaced", Font.PLAIN, 14));
        codeTextArea.setBackground(new Color(255, 255, 255));

        lineNumberComponent = new LineNumberComponent(codeTextArea);

        JScrollPane codeScrollPane = new JScrollPane(codeTextArea);
        codeScrollPane.setRowHeaderView(lineNumberComponent);
        codeScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        codeScrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        codeScrollPane.setBackground(backgroundGray);
        codeScrollPane.getViewport().setBackground(new Color(255, 255, 255));

        consoleTextArea = new JTextArea();
        consoleTextArea.setFont(new Font("Monospaced", Font.PLAIN, 13));
        consoleTextArea.setEditable(false);
        consoleTextArea.setBackground(new Color(30, 30, 30));
        consoleTextArea.setForeground(new Color(220, 220, 220));

        JScrollPane consoleScrollPane = new JScrollPane(consoleTextArea);
        consoleScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        consoleScrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        consoleScrollPane.setBorder(BorderFactory.createTitledBorder(" Consola de Resultados "));

        JPanel statusPanel = new JPanel(new BorderLayout());
        statusPanel.setBackground(backgroundGray);
        statusPanel.setBorder(BorderFactory.createEmptyBorder(2, 5, 2, 5));

        compileButton = new JButton("Compilar");
        compileButton.setBackground(Color.GREEN);
        compileButton.setForeground(Color.WHITE);
        compileButton.setCursor(new java.awt.Cursor(Cursor.HAND_CURSOR));
        compileButton.addActionListener(e -> compileButtonActionPerformed(e));

        JPanel leftStatusPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 0, 0));
        leftStatusPanel.setOpaque(false);
        leftStatusPanel.add(compileButton);
        statusPanel.add(leftStatusPanel, BorderLayout.WEST);

        statusLabel = new JLabel("Línea: 1 | Columna: 1");
        statusLabel.setFont(new Font("SansSerif", Font.PLAIN, 12));
        statusPanel.add(statusLabel, BorderLayout.EAST);

        JSplitPane splitPane = new JSplitPane(JSplitPane.VERTICAL_SPLIT, codeScrollPane, consoleScrollPane);
        splitPane.setResizeWeight(0.75);
        splitPane.setDividerLocation(350);
        splitPane.setBackground(backgroundGray);

        this.add(splitPane, BorderLayout.CENTER);
        this.add(statusPanel, BorderLayout.SOUTH);

        // Listener para actualizar el coloreado dinámicamente
        codeTextArea.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                triggerHighlight();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                triggerHighlight();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                triggerHighlight();
            }
        });

        // Listener para actualizar línea y columna
        codeTextArea.addCaretListener(new CaretListener() {
            @Override
            public void caretUpdate(CaretEvent e) {
                int lineNumber = 1;
                int columnNumber = 1;
                try {
                    int caretPos = codeTextArea.getCaretPosition();
                    String text = codeTextArea.getText();
                    if (caretPos <= text.length()) {
                        for (int i = 0; i < caretPos; i++) {
                            if (text.charAt(i) == '\n') {
                                lineNumber++;
                                columnNumber = 1;
                            } else {
                                columnNumber++;
                            }
                        }
                    }
                } catch (Exception ex) {
                    // Manejo de errores
                }
                statusLabel.setText("Línea: " + lineNumber + " | Columna: " + columnNumber);
            }
        });
    }

    /**
     * Método privado para inicializar los colores del editor.
     */
    private void inicializarColores() {
        colorSecciones = new Color(128, 0, 128); // Morado para secciones (VARIABILES>, etc.)
        colorKeywords = new Color(0, 0, 255); // Azul para palabras clave (si, ratio, actio, etc.)
        colorTipos = new Color(0, 128, 128); // Cian oscuro para tipos (numerus, textum, etc.)
        colorCadenas = new Color(0, 128, 0); // Verde para cadenas de texto
        colorComentarios = new Color(128, 128, 128); // Gris para comentarios
    }

    private void triggerHighlight() {
        if (isUpdatingHighlight) {
            return;
        }
        isUpdatingHighlight = true;

        javax.swing.SwingUtilities.invokeLater(() -> {
            applySyntaxHighlighting();
            isUpdatingHighlight = false;
        });
    }

    /**
     * Método encargado de analizar el texto y aplicar los colores configurados.
     */
    private void applySyntaxHighlighting() {
        StyledDocument doc = codeTextArea.getStyledDocument();
        String text = codeTextArea.getText();

        Style defaultStyle = StyleContext.getDefaultStyleContext().getStyle(StyleContext.DEFAULT_STYLE);
        StyleConstants.setForeground(defaultStyle, Color.BLACK);
        doc.setCharacterAttributes(0, text.length(), defaultStyle, true);

        coloringRegex(doc, text, "\\b(VARIABILES>|MUNERA>|MAIOR>)\\b", colorSecciones, true);
        coloringRegex(doc, text, "\\b(structura|ratio|actio|si|sino|dum|facere|per|reddere|finis|perge|interrumpe|verum|falsus)\\b", colorKeywords, true);
        coloringRegex(doc, text, "\\b(numerus|textum|decimalis|littera)\\b", colorTipos, false);
        coloringRegex(doc, text, "\"[^\"]*\"", colorCadenas, false);
        coloringRegex(doc, text, "//.*", colorComentarios, false);
        coloringRegex(doc, text, "##[\\s\\S]*?##", colorComentarios, false);
    }

    private void coloringRegex(StyledDocument doc, String text, String regex, Color color, boolean bold) {
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(text);

        Style style = doc.addStyle("Style_" + regex.hashCode(), null);
        StyleConstants.setForeground(style, color);
        StyleConstants.setBold(style, bold);

        while (matcher.find()) {
            doc.setCharacterAttributes(matcher.start(), matcher.end() - matcher.start(), style, false);
        }
    }

    private void compileButtonActionPerformed(ActionEvent evt) {
        consoleTextArea.setText("");
        String codigoFuente = codeTextArea.getText();

        if (codigoFuente.trim().isEmpty()) {
            printToConsole("Error: El editor está vacío.");
        } else {
            try {
                result = compiler.parseCode(codigoFuente);

                printToConsole("Código traducido de Codex latinus a PigLatin\n");
                printToConsole(result);

            } catch (Exception ex) {
                printToConsole("Error de compilación / análisis:");
                printToConsole(ex.getMessage());
            }
        }
    }

    public void printToConsole(String text) {
        consoleTextArea.setForeground(Color.GREEN);
        consoleTextArea.append(text + "\n");
    }

    public void clearConsole() {
        consoleTextArea.setText("");
    }
}
