package codex_latinus.frontend;

import codex_latinus.backend.Compiler;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTextArea;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.BadLocationException;

/**
 *
 * @author michael
 */
public class EditorPanel extends javax.swing.JPanel {

    private JTextArea codeTextArea;
    private JTextArea consoleTextArea;
    private JLabel statusLabel;
    private JButton compileButton;
    private LineNumberComponent lineNumberComponent;
    private Compiler compiler = new Compiler();

    /**
     * Creates new form EditorPanel
     */
    public EditorPanel() {
        initComponents();
        initCustomEditor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    public String getCodeText() {
        return codeTextArea.getText();
    }

    /**
     * Método para establecer el texto del código fuente en el editor.
     */
    public void setCodeText(String text) {
        codeTextArea.setText(text);
    }

    /**
     * Inicializa los componentes del editor de código, consola, números de
     * línea, botón compilar y barra de estado, configurando el fondo en tono
     * gris.
     */
    private void initCustomEditor() {
        this.setLayout(new BorderLayout());

        Color backgroundGray = new Color(240, 240, 240);
        this.setBackground(backgroundGray);

        // Editor de Código
        codeTextArea = new JTextArea();
        codeTextArea.setFont(new Font("Monospaced", Font.PLAIN, 14));
        codeTextArea.setTabSize(4);
        codeTextArea.setBackground(new Color(255, 255, 255));

        lineNumberComponent = new LineNumberComponent(codeTextArea);

        // Scroll responsivo para el editor de código con numeración de líneas
        JScrollPane codeScrollPane = new JScrollPane(codeTextArea);
        codeScrollPane.setRowHeaderView(lineNumberComponent);
        codeScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        codeScrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        codeScrollPane.setBackground(backgroundGray);
        codeScrollPane.getViewport().setBackground(new Color(255, 255, 255));

        // Área de consola de Resultados / Errores
        consoleTextArea = new JTextArea();
        consoleTextArea.setFont(new Font("Monospaced", Font.PLAIN, 13));
        consoleTextArea.setEditable(false);
        consoleTextArea.setBackground(new Color(30, 30, 30));
        consoleTextArea.setForeground(new Color(220, 220, 220));

        // Scroll responsivo para la consola
        JScrollPane consoleScrollPane = new JScrollPane(consoleTextArea);
        consoleScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        consoleScrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        consoleScrollPane.setBorder(BorderFactory.createTitledBorder(" Consola de Resultados "));

        // Panel inferior para Botón Compilar y Línea/Columna
        JPanel statusPanel = new JPanel(new BorderLayout());
        statusPanel.setBackground(backgroundGray);
        statusPanel.setBorder(BorderFactory.createEmptyBorder(2, 5, 2, 5));

        // Botón Compilar a la izquierda del panel inferior
        compileButton = new JButton("Compilar");
        compileButton.setBackground(Color.GREEN);
        compileButton.setForeground(Color.WHITE);
        compileButton.setCursor(new java.awt.Cursor(Cursor.HAND_CURSOR));
        compileButton.addActionListener(e -> compileButtonActionPerformed(e));

        JPanel leftStatusPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 0, 0));
        leftStatusPanel.setOpaque(false);
        leftStatusPanel.add(compileButton);
        statusPanel.add(leftStatusPanel, BorderLayout.WEST);

        // Etiqueta de Línea y Columna a la derecha
        statusLabel = new JLabel("Línea: 1 | Columna: 1");
        statusLabel.setFont(new Font("SansSerif", Font.PLAIN, 12));
        statusPanel.add(statusLabel, BorderLayout.EAST);

        // JSplitPane para dividir el editor y la consola
        JSplitPane splitPane = new JSplitPane(JSplitPane.VERTICAL_SPLIT, codeScrollPane, consoleScrollPane);
        splitPane.setResizeWeight(0.75); // 75% para el editor, 25% para la consola por defecto
        splitPane.setDividerLocation(350);
        splitPane.setBackground(backgroundGray);

        this.add(splitPane, BorderLayout.CENTER);
        this.add(statusPanel, BorderLayout.SOUTH);

        // Listener para actualizar dinámicamente la línea y columna según la posición del cursor
        codeTextArea.addCaretListener(new CaretListener() {
            @Override
            public void caretUpdate(CaretEvent e) {
                int lineNumber = 1;
                int columnNumber = 1;
                try {
                    int caretPos = codeTextArea.getCaretPosition();
                    lineNumber = codeTextArea.getLineOfOffset(caretPos);
                    columnNumber = caretPos - codeTextArea.getLineStartOffset(lineNumber) + 1;
                    lineNumber += 1;
                } catch (BadLocationException ex) {
                    // Manejo de errores
                }
                statusLabel.setText("Línea: " + lineNumber + " | Columna: " + columnNumber);
            }
        });
    }

    /**
     * Acción que se ejecuta al presionar el botón compilar.
     */
    private void compileButtonActionPerformed(ActionEvent evt) {
        consoleTextArea.setText("");
        printToConsole("Iniciando compilación...");
        String codigoFuente = codeTextArea.getText();

        if (codigoFuente.trim().isEmpty()) {
            printToConsole("Error: El editor está vacío.");
        } else {
            try {
                String result = compiler.parseCode(codigoFuente);

                printToConsole("Código traducido de Codex latinus a PigLatin\n");
                printToConsole(result);

            } catch (Exception ex) {
                printToConsole("Error de compilación / análisis:");
                printToConsole(ex.getMessage());
            }
        }
    }

    /**
     * Componente interno para renderizar los números de línea al costado del
     * JTextArea.
     */
    private class LineNumberComponent extends JPanel {

        private final JTextArea textArea;

        public LineNumberComponent(JTextArea textArea) {
            this.textArea = textArea;
            setBackground(new Color(230, 230, 230));
            setForeground(new Color(120, 120, 120));

            // Actualizar cuando cambie el texto o el tamaño de fuente
            textArea.getDocument().addDocumentListener(new DocumentListener() {
                @Override
                public void insertUpdate(DocumentEvent e) {
                    repaint();
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    repaint();
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                    repaint();
                }
            });
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            g.setFont(textArea.getFont());
            Font metrics = textArea.getFont();
            java.awt.FontMetrics fm = g.getFontMetrics(metrics);

            int startOffset = textArea.viewToModel2D(new java.awt.Point(0, 0));
            int endOffset = textArea.viewToModel2D(new java.awt.Point(textArea.getWidth(), textArea.getHeight()));

            try {
                int startLine = textArea.getLineOfOffset(startOffset);
                int endLine = textArea.getLineOfOffset(endOffset);

                for (int i = startLine; i <= endLine; i++) {
                    String lineNumStr = String.valueOf(i + 1);
                    int y = textArea.modelToView2D(textArea.getLineStartOffset(i)).getBounds().y + fm.getAscent();

                    g.drawString(lineNumStr, getWidth() - fm.stringWidth(lineNumStr) - 10, y);
                }
            } catch (Exception e) {
                // Manejo de excepciones por renderizado en tiempo real
            }

            setPreferredSize(new Dimension(45, textArea.getHeight()));
        }
    }

    /**
     * Método auxiliar para escribir mensajes o errores en la consola de
     * resultados.
     */
    public void printToConsole(String text) {
        consoleTextArea.setForeground(Color.GREEN);
        consoleTextArea.append(text + "\n");
    }

    /**
     * Método auxiliar para limpiar la consola.
     */
    public void clearConsole() {
        consoleTextArea.setText("");
    }
}
