package codex_latinus.frontend;

import codex_latinus.backend.errors.CompilationError;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author michael
 */
public class ErrorTablePanel extends javax.swing.JPanel {

    private JTable errorTable;
    private DefaultTableModel tableModel;
    
    /**
     * Creates new form ErrorTablePanel
     */
    public ErrorTablePanel() {
        initComponents();
        loadErrors(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void initTable(List<CompilationError> errors) {
        setLayout(new BorderLayout());

        // Definir columnas
        String[] columnNames = {"Tipo", "Descripción del Error", "Línea", "Columna"};
        
        tableModel = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        errorTable = new JTable(tableModel);
        
        // Agregar la tabla dentro de un JScrollPane para que se visualice correctamente
        JScrollPane scrollPane = new JScrollPane(errorTable);
        add(scrollPane, BorderLayout.CENTER);

        // Cargar los datos si existen
        loadErrors(errors);
    }
    
    /**
     * Carga o actualiza la lista de errores en el modelo de la tabla.
     */
    public void loadErrors(List<CompilationError> errors) {
        if (tableModel == null) return;
        
        tableModel.setRowCount(0);
        
        if (errors != null) {
            for (CompilationError err : errors) {
                Object[] rowData = {
                    err.getType(),
                    err.getMessage(),
                    err.getLine(),
                    err.getColumn()
                };
                tableModel.addRow(rowData);
            }
        }
    }
}