package codex_latinus.frontend;

import codex_latinus.backend.Compiler;
import codex_latinus.backend.errors.CompilationError;
import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author michael
 */
public class MainWindow extends javax.swing.JFrame {

    private static final String navText = "Codex Latinus";
    private final EditorPanel editorPanel = new EditorPanel();
    private Compiler compiler = new Compiler();

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        setTitle("Codex Latinus");
        setMinimumSize(new Dimension(685, 461));
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initStyles();
        navText("");
        initialPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        menuLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        openFileButton = new javax.swing.JButton();
        saveFileButton = new javax.swing.JButton();
        astButton = new javax.swing.JButton();
        symbolTableButton = new javax.swing.JButton();
        semanticErrorButton = new javax.swing.JButton();
        newFileButton = new javax.swing.JButton();
        lexerErrorButton = new javax.swing.JButton();
        sintaxErrorButton1 = new javax.swing.JButton();
        semanticErrorButton1 = new javax.swing.JButton();
        contentPane = new javax.swing.JPanel();
        navTextLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebarPanel.setBackground(new java.awt.Color(153, 51, 0));
        sidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLabel.setText("Menú de opciones");
        menuLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidebarPanel.add(menuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 10, 150, -1));
        sidebarPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, 10));

        openFileButton.setBackground(new java.awt.Color(153, 153, 0));
        openFileButton.setText("Abrir");
        openFileButton.setBorder(new javax.swing.border.MatteBorder(null));
        openFileButton.setBorderPainted(false);
        openFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(openFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 164, 35));

        saveFileButton.setBackground(new java.awt.Color(153, 153, 0));
        saveFileButton.setText("Guardar");
        saveFileButton.setBorder(new javax.swing.border.MatteBorder(null));
        saveFileButton.setBorderPainted(false);
        saveFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidebarPanel.add(saveFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 125, 164, 35));

        astButton.setBackground(new java.awt.Color(153, 153, 0));
        astButton.setText("AST");
        astButton.setBorder(new javax.swing.border.MatteBorder(null));
        astButton.setBorderPainted(false);
        astButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        astButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                astButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(astButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 164, 35));

        symbolTableButton.setBackground(new java.awt.Color(153, 153, 0));
        symbolTableButton.setText("Tabla de símbolos");
        symbolTableButton.setBorder(new javax.swing.border.MatteBorder(null));
        symbolTableButton.setBorderPainted(false);
        symbolTableButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        symbolTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symbolTableButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(symbolTableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 195, 164, 35));

        semanticErrorButton.setBackground(new java.awt.Color(153, 153, 0));
        semanticErrorButton.setText("Pila de procesos");
        semanticErrorButton.setBorder(new javax.swing.border.MatteBorder(null));
        semanticErrorButton.setBorderPainted(false);
        semanticErrorButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidebarPanel.add(semanticErrorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 335, 164, 35));

        newFileButton.setBackground(new java.awt.Color(153, 153, 0));
        newFileButton.setText("Nuevo");
        newFileButton.setBorder(new javax.swing.border.MatteBorder(null));
        newFileButton.setBorderPainted(false);
        newFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(newFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 164, 35));

        lexerErrorButton.setBackground(new java.awt.Color(153, 153, 0));
        lexerErrorButton.setText("Tabla de errores léxicos");
        lexerErrorButton.setBorder(new javax.swing.border.MatteBorder(null));
        lexerErrorButton.setBorderPainted(false);
        lexerErrorButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lexerErrorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lexerErrorButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(lexerErrorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 164, 35));

        sintaxErrorButton1.setBackground(new java.awt.Color(153, 153, 0));
        sintaxErrorButton1.setText("Tabla de errores sintácticos");
        sintaxErrorButton1.setBorder(new javax.swing.border.MatteBorder(null));
        sintaxErrorButton1.setBorderPainted(false);
        sintaxErrorButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sintaxErrorButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sintaxErrorButton1ActionPerformed(evt);
            }
        });
        sidebarPanel.add(sintaxErrorButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 265, 164, 35));

        semanticErrorButton1.setBackground(new java.awt.Color(153, 153, 0));
        semanticErrorButton1.setText("Tabla de errores semánticos");
        semanticErrorButton1.setBorder(new javax.swing.border.MatteBorder(null));
        semanticErrorButton1.setBorderPainted(false);
        semanticErrorButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        semanticErrorButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semanticErrorButton1ActionPerformed(evt);
            }
        });
        sidebarPanel.add(semanticErrorButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 164, 35));

        contentPane.setBackground(new java.awt.Color(153, 255, 51));
        contentPane.setLayout(new java.awt.BorderLayout());

        navTextLabel.setBackground(new java.awt.Color(0, 0, 0));
        navTextLabel.setForeground(new java.awt.Color(0, 255, 0));
        navTextLabel.setText("jLabel1");
        navTextLabel.setMinimumSize(new java.awt.Dimension(685, 461));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                    .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileButtonActionPerformed
        paintPanel(editorPanel);
        navText("Editor de código");
    }//GEN-LAST:event_newFileButtonActionPerformed

    private void openFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccionar archivo de código (Latín o PigLatin)");

        // Crear el filtro para permitir solo archivos .lat y .pig
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de Código (*.lat, *.pig)", "lat", "pig");
        fileChooser.setFileFilter(filter);

        int userSelection = fileChooser.showOpenDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToOpen = fileChooser.getSelectedFile();

            try {
                String contenido = new String(Files.readAllBytes(fileToOpen.toPath()), StandardCharsets.UTF_8);

                // 1. Mostrar el panel del editor en la interfaz principal
                paintPanel(editorPanel);

                // 2. Actualizar el texto de la ruta en la barra superior indicando el archivo abierto
                navText("Editor de código / " + fileToOpen.getName());

                // 3. Enviar el contenido leído al JTextArea del EditorPanel
                editorPanel.setCodeText(contenido);

                JOptionPane.showMessageDialog(this,
                        "Archivo abierto con éxito: " + fileToOpen.getName(),
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE);

            } catch (java.io.IOException e) {
                JOptionPane.showMessageDialog(this,
                        "Error al leer el archivo: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_openFileButtonActionPerformed

    private void astButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_astButtonActionPerformed
        ParserTreePanel treePanel = new ParserTreePanel();
        String dotContent = compiler.getLastDotCode();
        
        treePanel.renderGraph(dotContent);
        paintPanel(treePanel);
        navText("Árbol AST");
    }//GEN-LAST:event_astButtonActionPerformed

    private void symbolTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symbolTableButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_symbolTableButtonActionPerformed

    private void lexerErrorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lexerErrorButtonActionPerformed
        List<CompilationError> lexicalErrors = Compiler.getCompilationErrors().stream()
                .filter(e -> "LEXICO".equalsIgnoreCase(e.getType()))
                .collect(Collectors.toList());

        ErrorTablePanel panel = new ErrorTablePanel();
        panel.loadErrors(lexicalErrors);
        paintPanel(panel);
        navText("Tabla de errores léxicos");
    }//GEN-LAST:event_lexerErrorButtonActionPerformed

    private void sintaxErrorButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sintaxErrorButton1ActionPerformed
        List<CompilationError> syntaxErrors = Compiler.getCompilationErrors().stream()
                .filter(e -> "SINTACTICO".equalsIgnoreCase(e.getType()))
                .collect(Collectors.toList());

        ErrorTablePanel panel = new ErrorTablePanel();
        panel.loadErrors(syntaxErrors);
        paintPanel(panel);
        navText("Tabla de errores sintácticos");
    }//GEN-LAST:event_sintaxErrorButton1ActionPerformed

    private void semanticErrorButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semanticErrorButton1ActionPerformed
        List<CompilationError> semanticErrors = Compiler.getCompilationErrors().stream()
                .filter(e -> "SEMANTICO".equalsIgnoreCase(e.getType()))
                .collect(Collectors.toList());

        ErrorTablePanel panel = new ErrorTablePanel();
        panel.loadErrors(semanticErrors);
        paintPanel(panel);
        navText("Tabla de errores semánticos");
    }//GEN-LAST:event_semanticErrorButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton astButton;
    private javax.swing.JPanel contentPane;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton lexerErrorButton;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JLabel navTextLabel;
    private javax.swing.JButton newFileButton;
    private javax.swing.JButton openFileButton;
    private javax.swing.JButton saveFileButton;
    private javax.swing.JButton semanticErrorButton;
    private javax.swing.JButton semanticErrorButton1;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JButton sintaxErrorButton1;
    private javax.swing.JButton symbolTableButton;
    // End of variables declaration//GEN-END:variables

    private void paintPanel(JPanel panel) {
        contentPane.removeAll();
        contentPane.add(panel);
        contentPane.revalidate();
        contentPane.repaint();
    }

    /**
     * Genera los estilos de los componentes.
     */
    private void initStyles() {
        menuLabel.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        menuLabel.setForeground(Color.white);

        navTextLabel.setOpaque(true);
        navTextLabel.setBackground(Color.BLACK);
        navTextLabel.setForeground(new Color(0, 255, 0));
        navTextLabel.setFont(new java.awt.Font("Monospaced", java.awt.Font.BOLD, 13));
        navTextLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));

        SwingUtilities.updateComponentTreeUI(this);
    }

    private void navText(String optionMenu) {
        navTextLabel.setText(navText + "/" + optionMenu);
    }

    private void initialPanel() {
        paintPanel(editorPanel);
        navText("Editor de código");
    }
}
