package codex_latinus.frontend;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author michael
 */
public class ParserTreePanel extends javax.swing.JPanel {

    private JLabel imageLabel;
    private JScrollPane scrollPane;
    private ImageIcon originalIcon = null;
    private double zoomFactor = 1.0;

    /**
     * Creates new form ParserTree
     */
    public ParserTreePanel() {
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    private void initCustomComponents() {
        this.setLayout(new BorderLayout());

        imageLabel = new JLabel("No hay árbol AST generado aún.", SwingConstants.CENTER);
        imageLabel.setVerticalAlignment(SwingConstants.CENTER);

        scrollPane = new JScrollPane(imageLabel);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

        // Listener para el Zoom con la rueda del mouse (Ctrl + Scroll)
        scrollPane.addMouseWheelListener(new MouseWheelListener() {
            @Override
            public void mouseWheelMoved(MouseWheelEvent e) {
                if (originalIcon == null) {
                    return;
                }


                if (e.isControlDown()) {
                    e.consume();

                    if (e.getPreciseWheelRotation() < 0) {
                        zoomFactor *= 1.1;
                    } else {
                        zoomFactor /= 1.1;
                    }

                    zoomFactor = Math.max(0.1, Math.min(5.0, zoomFactor));

                    actualizarImagenZoom();
                }
            }
        });

        this.add(scrollPane, BorderLayout.CENTER);
    }

    /**
     * Actualiza el tamaño de la imagen en base al factor de zoom actual.
     */
    private void actualizarImagenZoom() {
        if (originalIcon == null) {
            return;
        }

        int nuevoAncho = (int) (originalIcon.getIconWidth() * zoomFactor);
        int nuevoAlto = (int) (originalIcon.getIconHeight() * zoomFactor);

        if (nuevoAncho <= 0 || nuevoAlto <= 0) {
            return;
        }

        Image imgEscalada = originalIcon.getImage().getScaledInstance(nuevoAncho, nuevoAlto, Image.SCALE_SMOOTH);
        imageLabel.setIcon(new ImageIcon(imgEscalada));
        imageLabel.revalidate();
        imageLabel.repaint();
    }

    /**
     * Recibe el código DOT de Graphviz, genera la imagen y la muestra en el
     * panel.
     *
     * @param dotCode Contenido en formato DOT del AST.
     */
    public void renderGraph(String dotCode) {
        if (dotCode == null || dotCode.trim().isEmpty()) {
            originalIcon = null;
            imageLabel.setIcon(null);
            imageLabel.setText("El código DOT está vacío.");
            return;
        }

        try {
            File tempDot = File.createTempFile("ast_graph", ".dot");
            File tempImg = File.createTempFile("ast_graph", ".png");
            tempImg.deleteOnExit();

            try (FileWriter writer = new FileWriter(tempDot)) {
                writer.write(dotCode);
            }

            ProcessBuilder processBuilder = new ProcessBuilder("dot", "-Tpng", tempDot.getAbsolutePath(), "-o", tempImg.getAbsolutePath());
            Process process = processBuilder.start();
            int exitCode = process.waitFor();

            if (exitCode == 0) {
                originalIcon = new ImageIcon(tempImg.getAbsolutePath());
                zoomFactor = 1.0; // Resetear zoom al generar un nuevo árbol
                imageLabel.setIcon(originalIcon);
                imageLabel.setText("");
            } else {
                originalIcon = null;
                imageLabel.setIcon(null);
                imageLabel.setText("Error al compilar Graphviz (Asegúrate de tenerlo instalado).");
                JOptionPane.showMessageDialog(this,
                        "Graphviz devolvió un código de salida no exitoso. ¿Está instalado 'dot' en tu PATH?",
                        "Error de Graphviz",
                        JOptionPane.ERROR_MESSAGE);
            }

            tempDot.delete();

        } catch (IOException | InterruptedException e) {
            originalIcon = null;
            imageLabel.setIcon(null);
            imageLabel.setText("Excepción al generar la imagen del AST.");
            JOptionPane.showMessageDialog(this,
                    "Error al procesar Graphviz: " + e.getMessage() + "\nVerifica que Graphviz esté instalado en el sistema.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            if (Thread.currentThread().isInterrupted()) {
                Thread.currentThread().interrupt();
            }
        }
    }
}
